lazyenvs: macOS-specific changes

diff --git a/home/.local/share/zsh/site-functions/rbenv b/home/.local/share/zsh/site-functions/rbenv
--- a/home/.local/share/zsh/site-functions/rbenv
+++ b/home/.local/share/zsh/site-functions/rbenv
@@ -1,12 +1,11 @@
 emulate -L zsh
 
-export RBENV_ROOT="$HOME/.local/opt/rbenv"
+export RBENV_ROOT="/usr/local/var/rbenv"
 export PATH="$RBENV_ROOT/bin:$PATH"
 
 if ! type -p rbenv > /dev/null 2>&1; then
-  echo "rbenv not found. To install, run the following commands:" >&2
-  echo "\tgit clone https://github.com/rbenv/rbenv.git ~/.local/opt/rbenv" >&2
-  echo "\tcd ~/.local/opt/rbenv && src/configure && make -C src" >&2
+  echo "rbenv not found. To install, run the following command:" >&2
+  echo "\tbrew install rbenv" >&2
   return 1
 fi
 
